# Generated by Django 3.2 on 2021-04-16 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sec_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('entry_date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('temp', models.FloatField()),
                ('soc_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.society')),
            ],
        ),
        migrations.CreateModel(
            name='InvalidVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('entry_date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('temp', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('No Mask', 'No Mask'), ('High Temperature', 'High Temperature')], max_length=50)),
                ('soc_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.society')),
            ],
        ),
    ]
