# Generated by Django 3.2 on 2021-04-18 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('soc_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.society')),
            ],
        ),
    ]
