# Generated by Django 3.2 on 2021-04-20 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_newvisitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='email',
        ),
        migrations.AddField(
            model_name='society',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
